"use client";

import { useState } from "react";

import { createEmptyPersona } from "@/lib/audience/factory";
import {
  COMPANY_SIZE_OPTIONS,
  CONTENT_TYPE_SUGGESTIONS,
  PLATFORM_SUGGESTIONS,
  SENIORITY_OPTIONS,
  STATUSES,
} from "@/lib/audience/options";
import type { Persona, PersonaDraft } from "@/lib/audience/types";

import {
  Button,
  Field,
  IconButton,
  SaveFeedback,
  SelectField,
  TagsInput,
  TextArea,
  TextInput,
} from "@/components/business/primitives";

export function PersonaEditor({
  initial,
  defaultSegmentId,
  segmentName,
  onClose,
  onSave,
}: {
  initial: Persona | null;
  defaultSegmentId: string;
  segmentName: string;
  onClose: () => void;
  onSave: (draft: PersonaDraft) => Promise<void>;
}) {
  const [draft, setDraft] = useState<Persona>(() =>
    initial ?? createEmptyPersona(defaultSegmentId),
  );
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const valid = draft.name.trim().length > 0;

  const update = (key: keyof Persona, value: string) =>
    setDraft({ ...draft, [key]: value });
  const updateList = (key: keyof Persona, values: string[]) =>
    setDraft({ ...draft, [key]: values });

  const submit = async () => {
    if (!valid || saving) return;
    setSaving(true);
    setError(null);
    try {
      const { id, createdAt, updatedAt, ...rest } = draft;
      if (id || createdAt || updatedAt) {
        // meta fields are regenerated by the service on save
      }
      await onSave(rest);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not save persona.");
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-start justify-center p-4 sm:p-6">
      <button
        type="button"
        aria-label="Close persona editor"
        className="anim-fade-in absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
        disabled={saving}
      />
      <div className="anim-pop-in glass-panel relative flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl">
        <div className="flex items-start justify-between gap-3 border-b border-white/[0.06] px-6 py-4">
          <div>
            <h3 className="font-display text-lg font-bold text-white">
              {initial ? "Edit Persona" : "Create Persona"}
            </h3>
            <p className="mt-0.5 text-sm text-zinc-500">
              A concrete buyer for the segment <span className="text-zinc-300">{segmentName}</span>.
            </p>
          </div>
          <IconButton icon="close" label="Close" onClick={onClose} />
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            void submit();
          }}
          className="flex-1 space-y-6 overflow-y-auto px-6 py-6"
        >
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <Field label="Persona name" error={draft.name.trim() ? undefined : "Name is required"}>
              <TextInput
                id="persona-name"
                value={draft.name}
                onChange={(v) => update("name", v)}
                placeholder="e.g. Procurement Omar"
                invalid={!draft.name.trim()}
              />
            </Field>
            <Field label="Status" optional>
              <SelectField id="persona-status" value={draft.status} onChange={(v) => update("status", v)} options={STATUSES} />
            </Field>
            <Field label="Short description" optional className="sm:col-span-2">
              <TextArea
                id="persona-description"
                value={draft.shortDescription}
                onChange={(v) => update("shortDescription", v)}
                placeholder="Two lines describing who this person is."
                rows={2}
              />
            </Field>
          </div>

          <GroupLabel>Who they are</GroupLabel>
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <Field label="Age range" optional>
              <TextInput id="age" value={draft.ageRange} onChange={(v) => update("ageRange", v)} placeholder="e.g. 30-45" />
            </Field>
            <Field label="Job / role" optional>
              <TextInput id="job" value={draft.job} onChange={(v) => update("job", v)} placeholder="e.g. Operations Director" />
            </Field>
            <Field label="Industry" optional>
              <TextInput id="industry" value={draft.industry} onChange={(v) => update("industry", v)} placeholder="e.g. Construction" />
            </Field>
            <Field label="Location" optional>
              <TextInput id="location" value={draft.location} onChange={(v) => update("location", v)} placeholder="City or country…" />
            </Field>
            <Field label="Company size" optional>
              <SelectField id="size" value={draft.companySize} onChange={(v) => update("companySize", v)} options={COMPANY_SIZE_OPTIONS} placeholder="Select…" />
            </Field>
            <Field label="Seniority" optional>
              <SelectField id="seniority" value={draft.seniority} onChange={(v) => update("seniority", v)} options={SENIORITY_OPTIONS} placeholder="Select…" />
            </Field>
          </div>

          <GroupLabel>How they think and buy</GroupLabel>
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <Field label="Primary goals" optional>
              <TagsInput id="pgoals" values={draft.primaryGoals} onChange={(v) => updateList("primaryGoals", v)} placeholder="What they must achieve" />
            </Field>
            <Field label="Secondary goals" optional>
              <TagsInput id="sgoals" values={draft.secondaryGoals} onChange={(v) => updateList("secondaryGoals", v)} placeholder="What would be nice" />
            </Field>
            <Field label="Pain points" optional>
              <TagsInput id="pains" values={draft.painPoints} onChange={(v) => updateList("painPoints", v)} />
            </Field>
            <Field label="Frustrations" optional>
              <TagsInput id="frustrations" values={draft.frustrations} onChange={(v) => updateList("frustrations", v)} />
            </Field>
            <Field label="Buying triggers" optional>
              <TagsInput id="triggers" values={draft.buyingTriggers} onChange={(v) => updateList("buyingTriggers", v)} />
            </Field>
            <Field label="Motivations" optional>
              <TagsInput id="motivations" values={draft.motivations} onChange={(v) => updateList("motivations", v)} />
            </Field>
            <Field label="Objections" optional>
              <TagsInput id="objections" values={draft.objections} onChange={(v) => updateList("objections", v)} />
            </Field>
            <Field label="Concerns" optional>
              <TagsInput id="concerns" values={draft.concerns} onChange={(v) => updateList("concerns", v)} />
            </Field>
            <Field label="Decision factors" optional>
              <TagsInput id="decision" values={draft.decisionFactors} onChange={(v) => updateList("decisionFactors", v)} placeholder="What tips the decision" />
            </Field>
            <Field label="Risks" optional>
              <TagsInput id="risks" values={draft.risks} onChange={(v) => updateList("risks", v)} />
            </Field>
            <Field label="Challenges" optional>
              <TagsInput id="challenges" values={draft.challenges} onChange={(v) => updateList("challenges", v)} />
            </Field>
            <Field label="Research behavior" optional>
              <TextArea id="research" value={draft.researchBehavior} onChange={(v) => update("researchBehavior", v)} rows={2} placeholder="How do they shop or research before buying?" />
            </Field>
          </div>

          <GroupLabel>How to reach and talk to them</GroupLabel>
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <Field label="Preferred platforms" optional>
              <TagsInput id="platforms" values={draft.preferredPlatforms} onChange={(v) => updateList("preferredPlatforms", v)} suggestions={PLATFORM_SUGGESTIONS} />
            </Field>
            <Field label="Preferred content types" optional>
              <TagsInput id="content" values={draft.preferredContentTypes} onChange={(v) => updateList("preferredContentTypes", v)} suggestions={CONTENT_TYPE_SUGGESTIONS} />
            </Field>
            <Field label="Communication preferences" optional>
              <TextInput id="comms" value={draft.communicationPreferences} onChange={(v) => update("communicationPreferences", v)} placeholder="e.g. Short, direct messages" />
            </Field>
            <Field label="What they care about" optional>
              <TextInput id="cares" value={draft.whatCaresAbout} onChange={(v) => update("whatCaresAbout", v)} placeholder="e.g. Reliability, speed, cost" />
            </Field>
            <Field label="Resonant message" optional>
              <TextArea id="message" value={draft.resonantMessage} onChange={(v) => update("resonantMessage", v)} rows={2} placeholder="The one message that would make them pay attention." />
            </Field>
            <Field label="Language / tone" optional>
              <TextInput id="tone" value={draft.languageTone} onChange={(v) => update("languageTone", v)} placeholder="e.g. Professional, plain English" />
            </Field>
            <Field label="CTA preference" optional>
              <TextInput id="cta" value={draft.ctaPreference} onChange={(v) => update("ctaPreference", v)} placeholder="e.g. Book a demo, Save for later" />
            </Field>
          </div>
        </form>

        <div className="flex items-center justify-between gap-3 border-t border-white/[0.06] px-6 py-4">
          <SaveFeedback state={saving ? "saving" : error ? "error" : "idle"} errorMessage={error} />
          <div className="flex items-center gap-2.5">
            <Button variant="ghost" onClick={onClose} disabled={saving}>
              Cancel
            </Button>
            <Button variant="primary" onClick={() => void submit()} disabled={!valid || saving}>
              {initial ? "Save changes" : "Create persona"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

function GroupLabel({ children }: { children: string }) {
  return (
    <div className="flex items-center gap-3 pt-1">
      <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">{children}</p>
      <div className="h-px flex-1 bg-white/[0.06]" />
    </div>
  );
}