"use client";

import { useState } from "react";

import { createEmptySegment } from "@/lib/audience/factory";
import {
  BUYING_AUTHORITY_OPTIONS,
  B2B_INDUSTRY_SUGGESTIONS,
  B2C_INTEREST_SUGGESTIONS,
  CHANNEL_SUGGESTIONS,
  COMPANY_REVENUE_OPTIONS,
  COMPANY_SIZE_OPTIONS,
  LOCATION_SUGGESTIONS,
  OBJECTION_SUGGESTIONS,
  PAIN_POINT_SUGGESTIONS,
  PRIORITIES,
  ROLES,
  SENIORITY_OPTIONS,
  STATUSES,
  TRIGGER_SUGGESTIONS,
} from "@/lib/audience/options";
import type { AudienceSegment, AudienceType, SegmentDraft } from "@/lib/audience/types";

import {
  Button,
  Field,
  IconButton,
  SaveFeedback,
  SelectField,
  TagsInput,
  TextArea,
  TextInput,
} from "@/components/business/primitives";

export function SegmentEditor({
  initial,
  suggestedType,
  onClose,
  onSave,
}: {
  initial: AudienceSegment | null;
  suggestedType: AudienceType;
  onClose: () => void;
  onSave: (draft: SegmentDraft) => Promise<void>;
}) {
  const [draft, setDraft] = useState<AudienceSegment>(() =>
    initial ?? createEmptySegment({ audienceType: suggestedType }),
  );
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const valid = draft.name.trim().length > 0 && Boolean(draft.audienceType);
  const isB2C = draft.audienceType === "B2C";

  const update = (key: keyof AudienceSegment, value: string) =>
    setDraft({ ...draft, [key]: value });
  const updateList = (key: keyof AudienceSegment, values: string[]) =>
    setDraft({ ...draft, [key]: values });

  const submit = async () => {
    if (!valid || saving) return;
    setSaving(true);
    setError(null);
    try {
      const { id, createdAt, updatedAt, ...rest } = draft;
      if (id || createdAt || updatedAt) {
        // meta fields are regenerated by the service on save
      }
      await onSave(rest);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not save segment.");
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-start justify-center p-4 sm:p-6">
      <button
        type="button"
        aria-label="Close segment editor"
        className="anim-fade-in absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
        disabled={saving}
      />
      <div className="anim-pop-in glass-panel relative flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl">
        <div className="flex items-start justify-between gap-3 border-b border-white/[0.06] px-6 py-4">
          <div>
            <h3 className="font-display text-lg font-bold text-white">
              {initial ? "Edit Segment" : "Create Audience Segment"}
            </h3>
            <p className="mt-0.5 text-sm text-zinc-500">
              Who you reach — personas and campaigns will build on this segment.
            </p>
          </div>
          <IconButton icon="close" label="Close" onClick={onClose} />
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            void submit();
          }}
          className="flex-1 space-y-6 overflow-y-auto px-6 py-6"
        >
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <Field label="Segment name" error={draft.name.trim() ? undefined : "Name is required"}>
              <TextInput
                id="segment-name"
                value={draft.name}
                onChange={(v) => update("name", v)}
                placeholder="e.g. SMB marketing managers"
                invalid={!draft.name.trim()}
              />
            </Field>
            <Field label="Audience type">
              <SelectField
                id="segment-type"
                value={draft.audienceType}
                onChange={(v) => update("audienceType", v as AudienceType)}
                options={["B2B", "B2C"]}
              />
            </Field>
            <Field label="Priority" optional>
              <SelectField id="segment-priority" value={draft.priority} onChange={(v) => update("priority", v)} options={PRIORITIES} />
            </Field>
            <Field label="Role" optional hint="Primary tells campaigns which segment matters most.">
              <SelectField id="segment-role" value={draft.role} onChange={(v) => update("role", v)} options={ROLES} />
            </Field>
            <Field label="Status" optional>
              <SelectField id="segment-status" value={draft.status} onChange={(v) => update("status", v)} options={STATUSES} />
            </Field>
            <Field label="Description" optional className="sm:col-span-2">
              <TextArea
                id="segment-description"
                value={draft.description}
                onChange={(v) => update("description", v)}
                placeholder="What makes this audience worth targeting?"
                rows={2}
              />
            </Field>
          </div>

          {isB2C ? (
            <>
              <GroupLabel>Consumer audience (B2C)</GroupLabel>
              <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <Field label="Location" optional>
                  <TagsInput id="loc" values={draft.location} onChange={(v) => updateList("location", v)} placeholder="Country or region…" suggestions={LOCATION_SUGGESTIONS} />
                </Field>
                <Field label="Age range" optional>
                  <TextInput id="age" value={draft.ageRange} onChange={(v) => update("ageRange", v)} placeholder="e.g. 25-44" />
                </Field>
                <Field label="Interests" optional>
                  <TagsInput id="interests" values={draft.interests} onChange={(v) => updateList("interests", v)} suggestions={B2C_INTEREST_SUGGESTIONS} />
                </Field>
                <Field label="Lifestyle" optional>
                  <TextInput id="lifestyle" value={draft.lifestyle} onChange={(v) => update("lifestyle", v)} placeholder="e.g. Busy urban professionals" />
                </Field>
                <Field label="Buying behavior" optional>
                  <TextInput id="behavior" value={draft.buyingBehavior} onChange={(v) => update("buyingBehavior", v)} placeholder="e.g. Research-heavy, comparison shoppers" />
                </Field>
                <Field label="Purchase frequency" optional>
                  <TextInput id="frequency" value={draft.purchaseFrequency} onChange={(v) => update("purchaseFrequency", v)} placeholder="e.g. Weekly / monthly / quarterly" />
                </Field>
                <Field label="Occupation" optional>
                  <TagsInput id="occupation" values={draft.occupation} onChange={(v) => updateList("occupation", v)} placeholder="e.g. Teacher, Freelancer" />
                </Field>
                <Field label="Income range" optional>
                  <TextInput id="income" value={draft.incomeRange} onChange={(v) => update("incomeRange", v)} placeholder="e.g. $40k - $60k" />
                </Field>
              </div>
            </>
          ) : (
            <>
              <GroupLabel>Business audience (B2B)</GroupLabel>
              <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <Field label="Location" optional>
                  <TagsInput id="loc" values={draft.location} onChange={(v) => updateList("location", v)} placeholder="Country or region…" suggestions={LOCATION_SUGGESTIONS} />
                </Field>
                <Field label="Industries" optional>
                  <TagsInput id="industries" values={draft.industries} onChange={(v) => updateList("industries", v)} suggestions={B2B_INDUSTRY_SUGGESTIONS} />
                </Field>
                <Field label="Company size" optional>
                  <SelectField id="size" value={draft.companySize} onChange={(v) => update("companySize", v)} options={COMPANY_SIZE_OPTIONS} placeholder="Select…" />
                </Field>
                <Field label="Company revenue" optional>
                  <SelectField id="revenue" value={draft.companyRevenue} onChange={(v) => update("companyRevenue", v)} options={COMPANY_REVENUE_OPTIONS} placeholder="Select…" />
                </Field>
                <Field label="Departments" optional>
                  <TagsInput id="departments" values={draft.department} onChange={(v) => updateList("department", v)} placeholder="e.g. Marketing, Procurement" />
                </Field>
                <Field label="Job titles" optional>
                  <TagsInput id="titles" values={draft.jobTitle} onChange={(v) => updateList("jobTitle", v)} placeholder="e.g. Marketing Manager" />
                </Field>
                <Field label="Seniority" optional>
                  <TagsInput id="seniority" values={draft.seniority} onChange={(v) => updateList("seniority", v)} suggestions={SENIORITY_OPTIONS} />
                </Field>
                <Field label="Decision maker" optional hint="Who says yes to the purchase.">
                  <TextInput id="decision" value={draft.decisionMakerRole} onChange={(v) => update("decisionMakerRole", v)} placeholder="e.g. Head of Ops" />
                </Field>
                <Field label="Buying authority" optional>
                  <SelectField id="authority" value={draft.buyingAuthority} onChange={(v) => update("buyingAuthority", v)} options={BUYING_AUTHORITY_OPTIONS} placeholder="Select…" />
                </Field>
                <Field label="Procurement process" optional>
                  <TextInput id="procurement" value={draft.procurementProcess} onChange={(v) => update("procurementProcess", v)} placeholder="e.g. Quote + approval" />
                </Field>
              </div>
            </>
          )}

          <GroupLabel>What this audience needs</GroupLabel>
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <Field label="Pain points" optional>
              <TagsInput id="pains" values={draft.painPoints} onChange={(v) => updateList("painPoints", v)} suggestions={PAIN_POINT_SUGGESTIONS} />
            </Field>
            <Field label="Buying triggers" optional hint="What makes them buy now.">
              <TagsInput id="triggers" values={draft.buyingTriggers} onChange={(v) => updateList("buyingTriggers", v)} suggestions={TRIGGER_SUGGESTIONS} />
            </Field>
            <Field label="Business goals" optional>
              <TagsInput id="goals" values={draft.businessGoals} onChange={(v) => updateList("businessGoals", v)} placeholder="e.g. Cut costs, scale sales" />
            </Field>
            <Field label="Objections" optional>
              <TagsInput id="objections" values={draft.objections} onChange={(v) => updateList("objections", v)} suggestions={OBJECTION_SUGGESTIONS} />
            </Field>
            <Field label="Preferred channels" optional>
              <TagsInput id="channels" values={draft.preferredChannels} onChange={(v) => updateList("preferredChannels", v)} suggestions={CHANNEL_SUGGESTIONS} />
            </Field>
            <Field label="Notes" optional className="sm:col-span-2">
              <TextArea id="notes" value={draft.notes} onChange={(v) => update("notes", v)} rows={2} placeholder="Anything else worth capturing about this audience." />
            </Field>
          </div>
        </form>

        <div className="flex items-center justify-between gap-3 border-t border-white/[0.06] px-6 py-4">
          <SaveFeedback state={saving ? "saving" : error ? "error" : "idle"} errorMessage={error} />
          <div className="flex items-center gap-2.5">
            <Button variant="ghost" onClick={onClose} disabled={saving}>
              Cancel
            </Button>
            <Button variant="primary" onClick={() => void submit()} disabled={!valid || saving}>
              {initial ? "Save changes" : "Create segment"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

function GroupLabel({ children }: { children: string }) {
  return (
    <div className="flex items-center gap-3 pt-1">
      <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">{children}</p>
      <div className="h-px flex-1 bg-white/[0.06]" />
    </div>
  );
}