import { BUSINESS_VERSION, type Business } from "./types";

export function createEmptyBusiness(): Business {
  return {
    version: BUSINESS_VERSION,
    updatedAt: new Date().toISOString(),
    profile: {
      businessName: "",
      industry: "",
      businessType: "",
      country: "",
      cityRegion: "",
      website: "",
      businessEmail: "",
      businessPhone: "",
      shortDescription: "",
      fullDescription: "",
    },
    valueProposition: {
      mainValue: "",
      usp: "",
      differentiators: [],
      problemSolved: "",
      solutionProvided: "",
    },
    products: [],
    targetMarket: {
      primaryMarket: "",
      customerType: "",
      countries: [],
      citiesRegions: [],
      industries: [],
      companySize: "",
      jobRoles: [],
      departments: [],
      decisionMakerType: "",
      ageRange: "",
      gender: "",
      interests: [],
      lifestyle: "",
      buyingBehavior: "",
      languages: [],
      preferredChannels: [],
    },
    businessGoals: [],
    marketingGoal: {
      primaryGoal: "",
      secondaryGoals: [],
      monthlyLeadTarget: "",
      monthlyRevenueTarget: "",
      marketingBudget: "",
      preferredChannels: [],
      targetConversionRate: "",
    },
    brandVoice: {
      tones: [],
      personality: "",
      wordsToUse: [],
      wordsToAvoid: [],
      communicationStyle: "",
      writingPreferences: "",
      additionalGuidelines: "",
    },
    brandIdentity: {
      primaryColor: "",
      secondaryColor: "",
      accentColor: "",
      backgroundColor: "",
      preferredFont: "",
      brandNotes: "",
      assets: [],
    },
  };
}